#!/usr/bin/env python3
"""CDE 检索结果 → 适应症归类统计（编者整理口径，非官方统计）。

输入：/tmp/cdt-trials.jsonl（cdt_crawler.py 的输出，每行一条试验）
输出：website/tools/cde_indications.py（聚合结果，提交进仓库）

归类规则（顺序匹配，取首个命中）：
1. 试验通俗题目含「生物等效」→ BE 试验（不进入适应症排名）
2. 适应症文本按 KEYWORD_MAP 关键词归入大类
3. 未命中 → 其他
用途：适应症排名 Top N 与 BE 占比统计；页面标注「编者归类，供参考」。
"""

import json
import re
import sys
from collections import Counter, OrderedDict
from pathlib import Path

KEYWORD_MAP = OrderedDict([
    ("健康受试者研究", ["健康受试者", "健康志愿者"]),
    ("肿瘤", ["癌", "肿瘤", "白血病", "淋巴瘤", "骨髓瘤", "肉瘤", "黑色素", "实体瘤"]),
    ("感染", ["感染", "病毒", "细菌", "真菌", "肺炎", "流感", "乙肝", "丙肝", "艾滋", "结核", "新冠", "幽门", "感冒", "败血症"]),
    ("影像诊断", ["造影", "成像", "超声对比"]),
    ("心血管", ["高血压", "心衰", "心力衰竭", "心绞痛", "冠心病", "动脉", "血栓", "卒中", "脑梗", "脑出血", "房颤", "心房", "心律", "高脂", "血脂", "心肌梗", "休克"]),
    ("糖尿病及代谢", ["糖尿病", "肥胖", "代谢", "高尿酸", "痛风", "体重", "尿素循环"]),
    ("中枢神经", ["抑郁", "精神", "失眠", "帕金森", "阿尔茨海默", "癫痫", "偏头痛", "分裂", "焦虑", "多动", "认知", "成瘾", "多发性硬化", "痴呆"]),
    ("消化/肝病", ["肝", "肝炎", "胃炎", "胃溃疡", "肠炎", "克罗恩", "溃疡性结肠", "胰腺", "胆囊", "消化不良", "胃食管", "消化性溃疡", "短肠", "腹泻", "便秘"]),
    ("呼吸", ["哮喘", "慢阻肺", "COPD", "鼻炎", "咳嗽", "肺纤维化", "支气管", "慢性阻塞性肺", "胸膜"]),
    ("自身免疫", ["自身免疫", "类风湿", "狼疮", "银屑病", "强直", "干燥", "硬皮", "皮肌炎", "脊柱关节"]),
    ("疼痛/麻醉", ["疼痛", "镇痛", "麻醉", "止痛", "术后"]),
    ("皮肤", ["皮炎", "湿疹", "痤疮", "斑秃", "脱发", "烧伤", "创面", "皮肤溃疡"]),
    ("眼科", ["黄斑", "青光眼", "近视", "视网膜", "干眼", "结膜炎", "角膜炎"]),
    ("血液病", ["贫血", "血友病", "血小板", "骨髓纤维", "地中海", "粒细胞", "骨髓增生异常"]),
    ("生殖/泌尿", ["前列腺", "子宫", "卵巢", "不育", "勃起", "膀胱", "肾病", "肾脏", "肾衰", "肾炎", "尿路", "尿失禁"]),
    ("骨/肌肉", ["骨关节炎", "骨质疏松", "肌萎缩", "骨折", "椎间盘"]),
    ("疫苗/预防", ["疫苗", "预防"]),
    ("中医证候", ["湿热", "血瘀", "气虚", "阴虚", "阳虚", "痰湿", "肝郁", "证候", "上火", "寒凝"]),
    ("其他", []),
])

BE_RE = re.compile(r"生物等效|BE 试验|BE试验|生物等效性")


def classify(rec):
    if BE_RE.search(rec.get("title", "")) or BE_RE.search(rec.get("indication", "")):
        return "BE 试验"
    text = rec.get("indication", "") or ""
    for cat, kws in KEYWORD_MAP.items():
        for kw in kws:
            if kw in text:
                return cat
    return "其他"


def main():
    src = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("/tmp/cdt-trials.jsonl")
    out = Path(sys.argv[2]) if len(sys.argv) > 2 else \
        Path(__file__).resolve().parent / "cde_indications.py"
    n = 0
    cats = Counter()
    years = Counter()
    for line in src.open(encoding="utf-8"):
        rec = json.loads(line)
        n += 1
        cats[classify(rec)] += 1
        m = re.match(r"CTR(\d{4})", rec.get("ctr", ""))
        if m:
            years[m.group(1)] += 1
    ranked = [(c, v) for c, v in cats.most_common() if c != "BE 试验"]
    be_n = cats.get("BE 试验", 0)
    out.write_text(
        "# Generated by aggregate_cde_indications.py — do not edit by hand.\n"
        "# 口径：登记检索结果逐条归类（编者整理，非官方统计）；BE=试验题目含「生物等效」。\n"
        "TRIALS_CRAWLED = %d\n"
        "BE_COUNT = %d\n"
        "INDICATION_RANKING = [\n%s\n]\n"
        "CRAWL_YEARLY = [\n%s\n]\n" % (
            n, be_n,
            ",\n".join("    (%r, %d)" % (c, v) for c, v in ranked),
            ",\n".join("    (%r, %d)" % (y, years[y]) for y in sorted(years)),
        ),
        encoding="utf-8",
    )
    print("trials=%d be=%d cats=%d years=%s" % (n, be_n, len(ranked), sorted(years)))
    for c, v in ranked[:15]:
        print("  %-10s %d" % (c, v))


if __name__ == "__main__":
    main()
