"""稽查发现对照表 data（zh-only）——与 build_audit_findings.py 配套。

内容约定：
- 条款定位仅在两处出现具体条号：(1) 官网已核实并公开解读的条文
  （2026 版 GCP 第十六/十九/二十九/三十二/五十一/五十二/五十三条，见
  gcp-2026.html / ich-e6r3.html）；(2) 其余发现锚定「章 · 主题」级，不臆造条号。
- E6(R3) 映射用 ich-e6r3.html 已公开的原则编号（1-11）与 Annex 1 章节名。
- 严重程度为编者归纳的稽查实践分级：严重=影响受试者权益/安全或数据可靠性的
  系统性发现；主要=违反 GCP/方案/SOP、需整改计划；一般=文档瑕疵或局部偏离。
- hot=True 表示稽查/核查中反复出现的高频发现。
"""

# 章（2026 版 GCP 六章结构，见 gcp-2026.html）
CHAPTERS = [
    ("ch1", "第一章 总则"),
    ("ch2", "第二章 伦理审查委员会"),
    ("ch3", "第三章 主要研究者和药物临床试验机构"),
    ("ch4", "第四章 申办者"),
    ("ch5", "第五章 数据治理"),
    ("ch6", "第六章 附则"),
]

# 主题分组（筛选与表格分组共用）
TOPICS = [
    ("icf", "知情同意"),
    ("personnel", "人员与授权"),
    ("ethics", "伦理审查"),
    ("records", "记录与文件"),
    ("data", "数据治理"),
    ("safety", "安全性报告"),
    ("drug", "试验药物管理"),
    ("pd", "方案偏离与整改"),
    ("oversight", "监查与供应商"),
    ("registry", "登记与公开"),
]

SEVERITY = [
    ("critical", "严重"),
    ("major", "主要"),
    ("minor", "一般"),
]

# 每条发现：topic, chapter, clause, severity, hot, finding, check, e6
FINDINGS = [
    # ---- 知情同意 ----
    dict(topic="icf", chapter="ch2", clause="第二章 · 知情同意", severity="critical", hot=True,
         finding="ICF 签署时间晚于试验相关程序开始（先筛查/给药/采血，后签署知情同意）",
         check="核对每名受试者 ICF 签署日期与首次试验程序日期的时间逻辑；抽查筛选记录中的实际操作时间。",
         e6="原则 2"),
    dict(topic="icf", chapter="ch2", clause="第二章 · 知情同意", severity="critical",
         finding="使用的 ICF 不是现行伦理批准版本（修订获批后仍在使用旧版）",
         check="核对 ICF 版本号与最新伦理批件的覆盖范围；检查新旧版本切换节点是否有交接记录。",
         e6="原则 2 / 3"),
    dict(topic="icf", chapter="ch3", clause="第三章 · 知情同意", severity="major", hot=True,
         finding="ICF 签署时间逻辑错误（受试者签署日期晚于研究者签署日期等）",
         check="按 ICF 审核清单逐份核对签字日期链（告知 → 受试者签署 → 研究者签署）。",
         e6="原则 2"),
    dict(topic="icf", chapter="ch3", clause="第三章 · 知情同意", severity="major",
         finding="知情同意过程无源文件记录（仅存签名页，无法证明充分告知与答疑）",
         check="检查同意过程记录（谈话记录、受试者笔记）是否归档到 TMF/ISF 对应分类。",
         e6="原则 2"),
    dict(topic="icf", chapter="ch3", clause="第三章 · 知情同意", severity="critical",
         finding="新版 ICF 获批后，未对在组受试者重新告知并签署",
         check="检查每次 ICF 修订后的再同意记录，覆盖全部在组受试者。",
         e6="原则 2 / 4"),
    dict(topic="icf", chapter="ch3", clause="第三章 · 知情同意", severity="major",
         finding="ICF 由未授权人员签署，或签署人的授权文件缺失",
         check="核对 ICF 签署人与授权分工表（Delegation Log）的一致性。",
         e6="原则 10"),
    # ---- 人员与授权 ----
    dict(topic="personnel", chapter="ch3", clause="第三章 · 人员与职责", severity="major", hot=True,
         finding="授权分工表未实时更新（人员离职/新增后仍显示原分工）",
         check="抽查近 3 个月人员变动与授权分工表更新记录；核对实际操作人与授权一致。",
         e6="原则 5 / 10"),
    dict(topic="personnel", chapter="ch3", clause="第三章 · 人员与职责", severity="major", hot=True,
         finding="培训记录缺失，或培训日期晚于开始执行任务日期",
         check="核对培训日期与首次执行任务日期先后；新成员/新方案/新系统培训均有记录。",
         e6="原则 5"),
    dict(topic="personnel", chapter="ch3", clause="第三章 · 人员与职责", severity="major",
         finding="资质文件不全（简历、执业证书缺失或过期）",
         check="建立资质文件台账，核查证书有效期；到期前安排更新。",
         e6="原则 5"),
    dict(topic="personnel", chapter="ch3", clause="第三章 · 人员与职责", severity="critical",
         finding="超出授权范围执行任务（未被授权的人员执行研究者职责）",
         check="对照授权分工表抽查关键操作（知情同意、疗效评估、开医嘱）的签名人。",
         e6="原则 10"),
    dict(topic="personnel", chapter="ch3", clause="第十九条 · 主要研究者责任", severity="major",
         finding="PI 变更未及时记录或未按程序通报（现场最终责任人不明确）",
         check="检查 PI 变更的批准/通报记录；确认新 PI 的资质与培训记录完整。",
         e6="原则 10"),
    # ---- 伦理审查 ----
    dict(topic="ethics", chapter="ch2", clause="第二章 · 伦理审查", severity="critical",
         finding="方案或 ICF 修订在获得伦理批准之前已实施",
         check="核对修订版本生效日期与伦理批件日期；建立「批件—版本」对照表。",
         e6="原则 3"),
    dict(topic="ethics", chapter="ch2", clause="第二章 · 伦理审查", severity="major",
         finding="定期/年度跟踪审查未按期递交",
         check="维护伦理审查日历（批件到期日、年度报告截止日），到期前递交并留存回执。",
         e6="原则 3"),
    dict(topic="ethics", chapter="ch2", clause="第二章 · 伦理审查", severity="critical",
         finding="伦理要求的安全性报告（SAE/SUSAR 等）未递交或逾期",
         check="核对伦理递交记录与 SAE/SUSAR 清单的一致性。",
         e6="原则 3 / Annex 1 安全性报告"),
    dict(topic="ethics", chapter="ch2", clause="第二章 · 伦理审查", severity="critical",
         finding="伦理批件与实施文件版本不一致（批准 v1.1，实施 v1.0）",
         check="建立「批件—文件版本」对照表，随每次修订更新。",
         e6="原则 3"),
    dict(topic="ethics", chapter="ch2", clause="第十六条 · 伦理记录保存", severity="major",
         finding="伦理审查记录保存不符合期限要求（获批上市后 5 年 / 终止后 5 年）",
         check="建立伦理记录保存期限台账与到期处置流程。",
         e6="原则 9.5"),
    # ---- 记录与文件 ----
    dict(topic="records", chapter="ch3", clause="第三章 · 记录与报告", severity="major", hot=True,
         finding="ISF/TMF 文件缺失或索引无法定位（调阅困难）",
         check="按 TMF 分类参考做月度自查；做一次模拟调阅演练（抽查 10 份文件）。",
         e6="原则 9.4"),
    dict(topic="records", chapter="ch4", clause="第四章 · 记录与文件", severity="major", hot=True,
         finding="现行版与历史版文件混放，版本控制失效",
         check="检查文档区/目录的版本隔离与标识；历史版单独归档并注明作废。",
         e6="原则 8"),
    dict(topic="records", chapter="ch3", clause="第三章 · 记录与报告", severity="major",
         finding="源文件涂改覆盖（无单线划改、无签名和日期）",
         check="抽查源文件更正方式；SOP 中明确更正规则并培训。",
         e6="原则 9.4"),
    dict(topic="records", chapter="ch4", clause="第二十九条 · 必备记录保存", severity="major",
         finding="必备记录保存期限未建立台账、无到期处置流程",
         check="建立保存期限台账（同第十六条口径），明确到期后的处置与审批。",
         e6="原则 9.5"),
    dict(topic="records", chapter="ch4", clause="第四章 · 监查", severity="major",
         finding="监查报告缺失或严重滞后（访视后长期无报告）",
         check="核对访视→报告时限；建立监查报告跟进台账。",
         e6="原则 7 / Annex 1 监查"),
    dict(topic="records", chapter="ch4", clause="第四章 · 质量管理", severity="minor", hot=True,
         finding="SOP 与实际操作不一致（文件一套、实际一套）",
         check="抽查 SOP 执行证据与流程一致性；SOP 修订与实际流程同步。",
         e6="原则 6"),
    # ---- 数据治理（第五章，2026 版新增）----
    dict(topic="data", chapter="ch5", clause="第五十三条 · 计算机化系统", severity="critical",
         finding="计算机化系统无稽查轨迹，或轨迹不完整（数据修改无痕迹）",
         check="验证系统审计追踪功能覆盖关键数据要素；保留轨迹配置与抽查记录。",
         e6="原则 9.4 / Annex 1 数据治理"),
    dict(topic="data", chapter="ch5", clause="第五十一条 · 数据治理", severity="critical",
         finding="数据更正无受控流程（直接改库、无理由与审批记录、更正不可追溯）",
         check="检查数据更正记录是否含原因、审批与时间戳；SOP 明确更正流程。",
         e6="原则 9.4 / Annex 1 数据治理"),
    dict(topic="data", chapter="ch5", clause="第五十三条 · 计算机化系统", severity="critical",
         finding="系统未经验证，或试验期间未保持验证有效状态（换版后未再验证）",
         check="检查验证文件包与当前版本对应；建立版本变更触发再验证的机制。",
         e6="Annex 1 数据治理"),
    dict(topic="data", chapter="ch5", clause="第五十三条 · 用户与权限", severity="major",
         finding="共享账号，或用户权限与职责、盲法设置不符",
         check="核对用户清单与授权分工表；按职责最小化授权并定期审查。",
         e6="原则 10 / Annex 1 数据治理"),
    dict(topic="data", chapter="ch5", clause="第五十三条 · 电子签名", severity="critical",
         finding="电子签名不合规（代签、共用密码、签名与职责不符）",
         check="检查电子签名策略与培训记录；禁止账号共享并抽查登录日志。",
         e6="Annex 1 数据治理"),
    dict(topic="data", chapter="ch5", clause="第五十三条 · 系统问题管理", severity="major",
         finding="系统问题无记录、无定期审查（无 issue log）",
         check="建立系统问题日志；定期审查识别系统性问题并留痕。",
         e6="Annex 1 数据治理"),
    dict(topic="data", chapter="ch5", clause="第五十一条 · 数据传输", severity="major",
         finding="系统间数据传输未经验证流程（手工搬数无校验）",
         check="检查数据传输的校验记录与流程文件。",
         e6="Annex 1 数据治理"),
    dict(topic="data", chapter="ch5", clause="第五十二条 · 盲态完整性", severity="critical",
         finding="非盲信息访问权限未界定、未记录（盲态完整性风险）",
         check="检查权限设计是否覆盖盲态角色清单；确认可访问非盲信息的角色、职责已文档化。",
         e6="Annex 1 数据治理"),
    dict(topic="data", chapter="ch5", clause="第五十二条 · 盲态完整性", severity="major",
         finding="揭盲/意外破盲未记录、未评估影响",
         check="检查破盲记录与影响评估；必要时与 SAE 报告关联归档。",
         e6="Annex 1 数据治理"),
    dict(topic="data", chapter="ch5", clause="第五十一条 · 数据治理", severity="major",
         finding="统计分析前未按预定程序对数据集做最终确认",
         check="检查最终数据集确认记录与审批链。",
         e6="原则 9.4"),
    dict(topic="data", chapter="ch5", clause="第五十一条 · 元数据", severity="major",
         finding="采集数据缺少元数据（无来源、无时间戳）",
         check="抽查关键数据要素的元数据完整性（含计算机化系统直接采集的数据）。",
         e6="Annex 1 数据治理"),
    dict(topic="data", chapter="ch5", clause="第五十三条 · 备份与应急", severity="major",
         finding="电子数据无备份，或备份不可恢复",
         check="检查备份策略与恢复演练记录；故障应急措施是否可执行。",
         e6="Annex 1 数据治理"),
    # ---- 安全性报告 ----
    dict(topic="safety", chapter="ch4", clause="第四章 · 安全性报告", severity="critical", hot=True,
         finding="SAE 报告超时限（未在 24 小时内向申办者提供书面报告，以现行法规/方案时限为准）",
         check="建立时限台账并定期回溯（参考时限日历工具）；核对 SAE 首报/随访报链。",
         e6="Annex 1 安全性报告"),
    dict(topic="safety", chapter="ch4", clause="第四章 · 安全性报告", severity="critical",
         finding="SUSAR 未按要求递交（致死/危及生命 7 天、其他 15 天，以现行要求为准）",
         check="核对 SUSAR 递交记录与法规时限的符合性。",
         e6="Annex 1 安全性报告"),
    dict(topic="safety", chapter="ch4", clause="第四章 · 安全性报告", severity="major",
         finding="源数据中存在的 AE 未录入/漏报",
         check="抽查源数据（病历、化验单）与 AE 列表的一致性。",
         e6="原则 9.4"),
    dict(topic="safety", chapter="ch4", clause="第四章 · 安全性报告", severity="major",
         finding="SAE 报告内容与源数据不一致",
         check="核对 SAE 表格与源记录的字段一致性（起止时间、因果关系、结局）。",
         e6="原则 9.4"),
    dict(topic="safety", chapter="ch4", clause="第四章 · 安全性报告", severity="major",
         finding="安全性更新报告（如 DSUR）未递交或逾期",
         check="核查递交日历与接收回执。",
         e6="Annex 1 安全性报告"),
    # ---- 试验药物管理 ----
    dict(topic="drug", chapter="ch3", clause="第三章 · 试验药物管理", severity="major", hot=True,
         finding="温湿度记录断档，或超范围未按预案处置",
         check="检查温湿度记录连续性；异常处置记录与设备异常预案是否执行。",
         e6="原则 11"),
    dict(topic="drug", chapter="ch3", clause="第三章 · 试验药物管理", severity="major",
         finding="药物清点记录与库存不符",
         check="稽查前预清点；建立收发存账实核对机制。",
         e6="原则 11"),
    dict(topic="drug", chapter="ch3", clause="第三章 · 试验药物管理", severity="critical",
         finding="药物发放不符合随机化/方案要求",
         check="核对发放记录与随机化方案（随机号、组别、访视窗）。",
         e6="原则 11"),
    dict(topic="drug", chapter="ch3", clause="第三章 · 试验药物管理", severity="major",
         finding="效期管理缺失（过期药物未隔离）",
         check="检查效期台账与隔离区标识；临期药物提前处置。",
         e6="原则 11"),
    dict(topic="drug", chapter="ch3", clause="第三章 · 试验药物管理", severity="minor",
         finding="回收/销毁记录不完整",
         check="核对发放—回收—销毁链条的签名与数量逻辑。",
         e6="原则 11"),
    # ---- 方案偏离与整改 ----
    dict(topic="pd", chapter="ch3", clause="第三章 · 方案执行", severity="major",
         finding="方案偏离未记录或未分级评估（重要偏离未报伦理）",
         check="检查偏离日志完整性（参考 PD 决策树工具）；重要偏离的伦理报告记录。",
         e6="原则 7 / 9"),
    dict(topic="pd", chapter="ch4", clause="第四章 · 质量管理", severity="major",
         finding="CAPA 未闭环（发现 → 纠正 → 预防链条断裂）",
         check="抽查 CAPA 关闭证据（根因分析、纠正措施、有效性确认）。",
         e6="原则 6 / 9"),
    dict(topic="pd", chapter="ch4", clause="第四章 · 质量管理", severity="major",
         finding="质量风险识别与缓解措施未文档化（关键质量因素无管理计划）",
         check="检查质量计划与风险记录；风险相称原则是否体现在监查/稽查计划中。",
         e6="原则 6 / 7"),
    # ---- 监查与供应商 ----
    dict(topic="oversight", chapter="ch4", clause="第四章 · 监查", severity="major",
         finding="监查计划未按风险相称原则制定，或长期未更新",
         check="核对监查计划与风险评估的联动更新记录。",
         e6="原则 7 / Annex 1 监查"),
    dict(topic="oversight", chapter="ch4", clause="第三十二条 · 申办者责任", severity="major",
         finding="CRO/供应商协议未明确责任与监督安排（责任可委托不可转移）",
         check="复核外包合同的责任条款；确认协议与 2026 版 GCP 第三十二条口径一致。",
         e6="原则 10.1"),
    dict(topic="oversight", chapter="ch4", clause="第三十二条 · 申办者责任", severity="major",
         finding="对 CRO/供应商的监督记录缺失（oversight 无据可查）",
         check="检查监督记录（会议纪要、绩效报告、问题升级记录）。",
         e6="原则 10.1"),
    dict(topic="oversight", chapter="ch4", clause="第四章 · 供应商管理", severity="minor",
         finding="供应商资质评估文件不全",
         check="核查供应商评估档案（资质、经验、质量体系）。",
         e6="原则 10"),
    # ---- 登记与公开 ----
    dict(topic="registry", chapter="ch4", clause="第四章 · 注册登记", severity="major",
         finding="试验登记信息与方案不一致，或重大变更未及时更新",
         check="核对登记平台信息与现行方案版本的一致性。",
         e6="原则 9.6"),
    dict(topic="registry", chapter="ch4", clause="第四章 · 结果公开", severity="minor",
         finding="试验结果公开逾期或缺失",
         check="检查结果递交日历与公开记录。",
         e6="原则 9.6"),
]
